name: skyguru
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  flutter_spinkit: ^5.2.1
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_native_splash:
  android: true
  ios: false
  web: true

  color: "#d4e4ed"
  image: "lib/assets/logo.png"

  android_12:
    color: "#d4e4ed"
    image: "lib/assets/logo.png"
